name: Package state-observation

# This workflow only runs when pushing to master or pushing a tag
#
# On master, it will:
# - Build packages for selected Debian/Ubuntu distro
# - Upload the packages to https://dl.bintray.com/arntanguy/ppa-head

on:
  push:
    branches:
      - master
      - topic/packaging

jobs:
  # This job build binary packages for Ubuntu
  build-packages:
    strategy:
      fail-fast: false
      matrix:
        dist: [bionic, focal]
        arch: [amd64]
    runs-on: ubuntu-18.04 
    steps:
    - uses: actions/checkout@v1
    - name: Prepare recipe
      run: |
        set -x
        cp .github/workflows/state-observation.recipe /tmp/state-observation.recipe
        export REF=`echo ${{ github.ref }} | sed -e 's@refs/[a-z]*/@@'`
        sed -i "s#@REF@#${REF}#" /tmp/state-observation.recipe
        echo "Prepared recipe"
        echo "###############"
        cat /tmp/state-observation.recipe
    - name: Build package
      uses: jrl-umi3218/github-actions/build-package@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        recipe: /tmp/state-observation.recipe
    - uses: actions/upload-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
        path: /tmp/packages-${{ matrix.dist }}-${{ matrix.arch }}/
  # This job upload binary packages for Ubuntu
  upload-packages:
    needs: build-packages
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        dist: [bionic,focal]
        arch: [amd64]
    runs-on: ubuntu-18.04 
    steps:
    - name: Download packages
      uses: actions/download-artifact@v1
      with:
        name: packages-${{ matrix.dist }}-${{ matrix.arch }}
    - name: Upload
      uses: jrl-umi3218/github-actions/upload-package@master
      with:
        dist: ${{ matrix.dist }}
        arch: ${{ matrix.arch }}
        subject: arntanguy
        repo: ppa-head
        package: |
          name: state-observation-dev
          desc: "state-observation library for state-observation"
          licenses: [BSD 2-Clause]
          vcs_url: https://github.com/jrl-umi3218/state-observation
        version: 1.3.3 
        path: packages-${{ matrix.dist }}-${{ matrix.arch }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
